### ISSUE TITLE
Create an authomatic mechanism to download the free book of the day

### ISSUE THREAD

**Issue by andreybleme** [gleidiin/free-e-books#1]
Would be nice to have all those free books without needing to enter on that website every day \o

Can we create a robot to do the dirty work for us? :disappointed_relieved: 
http://www.seleniumhq.org/

**Comment by gleidiin** [comment]
Hi @andreybleme we can make it. What do you think about create a new project to do this? Cuz this one is only to keep the files saved and I read about this selenium that you've posted, it seems like a tool to testing web solutions. Is this an ideal tool to build a web robot? I don't know much about these tools.
